# Fail2ban filter for nginx bot login attempts
[Definition]
failregex = ^<HOST> -.*"(GET|POST) /admin/.*" 401
            ^<HOST> -.*"(GET|POST) /bot2/.*" 401
            ^<HOST> -.*"(GET|POST) /grafana/.*" 401
ignoreregex =